baseURL = 'https://burgas-69.netlify.app/'
languageCode = 'en-us'
title = 'Планктон'
theme = 'Burgas'

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  description = "Дигитална платформа за представяне на късометражни и среднометражни филми, насочена към българската публика. Всяка седмица по един нов филм, достъпен за гледане безплатно."

[params.seo]
  site_name    = "Burgas Film Fest"
  defaultImage = "/img/og-default.jpg"   # put the file in /static/img/og-default.jpg
  twitterSite  = "@your_account"
  locale       = "bg_BG"

[outputs]
  home = ["HTML", "RSS"]

  [params.org]
  name = "Plakton"
  url  = "https://plakton.bg/"
  logo = "/img/logo-512.png"            # add this file under /static/img/
  sameAs = [
    "https://www.facebook.com/burgasfilmfest",
    "https://www.instagram.com/plankton_space/"
  ]