baseURL = "https://plankton.bg/"
languageCode = "bg-bg"
title = "Планктон"
theme = "Burgas"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS"]

[params]
description = "Дигитална платформа за представяне на късометражни и среднометражни филми, насочена към българската публика. Всяка седмица по един нов филм, достъпен за гледане безплатно."

[params.seo]
site_name = "Планктон"
defaultImage = "/img/og-default.jpg"
locale = "bg_BG"
twitterCard = "summary_large_image"
twitterSite = "@your_account"

[params.org]
name = "Plankton"
url = "https://plankton.bg/"
logo = "/img/og-default.jpg"
sameAs = ["https://www.facebook.com/burgasfilmfest", "https://www.instagram.com/plankton_space/"]

[[params.partners]]
url = "https://ncf.bg/bg"
img = "/img/NFK LOGO INV in PNG.png"
alt = "National Culture Fund"

[[params.partners]]
url = "https://another.example"
img = "/img/zlogo_biff_full_transparent_0copy.png"
alt = "Burgas Film Fest"

[[params.partners]]
url = "https://another.example"
img = "/img/пейския_съюз_RGB_WHITE_Outline  - Copy.png"
alt = "European Union Funding"

[[params.partners]]
url = "https://ncf.bg/bg"
img = "/img/NFK LOGO INV in PNG.png"
alt = "National Culture Fund (Inverse)"

[[params.partners]]
url = "https://another.example"
img = "/img/zlogo_biff_full_transparent_0copy.png"
alt = "Burgas Film Fest"

[[params.partners]]
url = ""
img = "/img/пейския_съюз_RGB_WHITE_Outline  - Copy.png"
alt = "European Union Funding (Alt)"
