backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  # -------------------------
  # Posters
  # -------------------------
  - name: "posters"
    label: "Posters"
    folder: "content/posters"
    create: true
    slug: "{{year}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  # -------------------------
  # Films
  # -------------------------
  - name: "films"
    label: "Films"
    folder: "content/films"
    create: true
    # Example: 2069-test-ime-2069
    slug: "{{year}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      # Basics / routing
      - { label: "Page Title", name: "title", widget: "string" }                # e.g. "Test ime (2069)"
      - { label: "Film Title", name: "film_title", widget: "string" }           # e.g. "Test ime"
      - { label: "URL Slug", name: "slug", widget: "string", required: false }  # optional override
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }

      # Canonical film info
      - { label: "Country", name: "country", widget: "string" }
      - { label: "Year", name: "year", widget: "number" }
      - { label: "Minutes", name: "minutes", widget: "number" }
      - { label: "Short Description", name: "description", widget: "text" }

      # Dates
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Last Modified", name: "lastmod", widget: "datetime", required: false }

      # Images
      - label: "Images (array)"
        name: "images"
        widget: "list"
        allow_add: true
        field:
          label: "Image"
          name: "image"
          widget: "image"
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Feature Image", name: "feature_image", widget: "image", required: false }

      # Video / streaming
      - { label: "Watch Button Visible", name: "show_watch_button", widget: "boolean", default: true, required: false }
      - { label: "Video ID", name: "video_id", widget: "string", required: false }
      - { label: "Hero Video ID", name: "hero_video_id", widget: "string", required: false }
      - { label: "Stream Duration (ribbon)", name: "stream_duration", widget: "string", required: false }

      # Credits (keep both forms if your templates read either)
      - { label: "director (lowercase)", name: "director", widget: "string", required: false }
      - { label: "Director (Capitalized)", name: "Director", widget: "string", required: false }
      - { label: "Producers", name: "Producers", widget: "string", required: false }
      - { label: "Actors", name: "Actors", widget: "string", required: false }
      - { label: "Screenwriter", name: "Screenwriter", widget: "string", required: false }
      - { label: "Genre", name: "Genre", widget: "string", required: false }
      - { label: "Text Author", name: "text_author", widget: "string", required: false }

      # Page body
      - { label: "Body", name: "body", widget: "markdown", required: false }

      # SEO (optional, matches your front matter)
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - { label: "Type", name: "type", widget: "select", options: ["article","website","video.other"], default: "article", required: false }
          - { label: "Twitter Card", name: "twitterCard", widget: "select", options: ["summary","summary_large_image"], default: "summary_large_image", required: false }
          - { label: "Noindex", name: "noindex", widget: "boolean", default: false, required: false }
